### ISSUE TITLE
عدم قرار دادن کد های مربوط به تست در کد main

### ISSUE THREAD

**Issue by SaeedMasoumi** [rezaiyan/Moviz#1]
https://github.com/rezaiyan/Moviz/blob/a9cc67cdd5a91acccf09668664a2227cedb05532/sdk-base/src/main/java/ir/alirezaiyan/moviz/sdk/base/test/InjectMocksRule.kt#L6

مثلا اینجا کدهایی که قراره تو پکیج تست استفاده بشه تو کد اصلی هست. بهتره این چیزهای مربوط به تست بشن یه ماژول و حالا تو 
testImplementation
استفاده بشه

**Comment by rezaiyan** [comment]
Was done in this commit https://github.com/rezaiyan/Moviz/commit/215e337d0761f610a73e437d07f6f93bc8dcbbc9
