### ISSUE TITLE
اسکوپ های بیش از اندازه

### ISSUE THREAD

**Issue by SaeedMasoumi** [rezaiyan/Moviz#2]
https://github.com/rezaiyan/Moviz/blob/a9cc67cdd5a91acccf09668664a2227cedb05532/sdk-platform/src/main/java/ir/alirezaiyan/moviz/sdk/platform/interactor/UseCase.kt#L15

به ازای هر اسکوپ یه coroutinescope جدید ساخته میشه.
از نظر پرفرمنسی خوب نیست، و کلا هم یوزکیس نبودش هم اوکیه یعنی میتونی بدون اینکه یوزکیس داشته باشی اینکارو انجام بدی

**Comment by rezaiyan** [comment]
Was done in this commit https://github.com/rezaiyan/Moviz/commit/8849f3d902eda9237e0ff787bef91648534f0077
