### ISSUE TITLE
مشکل با ماژول sdk-platform

### ISSUE THREAD

**Issue by SaeedMasoumi** [rezaiyan/Moviz#3]
https://github.com/rezaiyan/Moviz/blob/a9cc67cdd5a91acccf09668664a2227cedb05532/sdk-platform/src/main/java/ir/alirezaiyan/moviz/sdk/platform/platform/BaseActivity.kt#L16

هم کد های بیزینس لاجیکی مثل usecase رو این ماژول داره هم چیزهای مربوط به اندروید 

بهتره هرچیزی که مربوط به اندروید و ui هست رو ببری تو ماژول دیگه ای به اسم
android-ui یا هرچیزی و چیزایی مثل یوزکیس و اینا برن تو ماژول دیگه ای مثل 
sdk, common, domain , ...

**Comment by rezaiyan** [comment]
Was done in this commit https://github.com/rezaiyan/Moviz/commit/5c250fed9e2305f14c5f49f72be02fedf34902dd
