### ISSUE TITLE
اشتباه در پیاده سازی ریپازیتوری

### ISSUE THREAD

**Issue by SaeedMasoumi** [rezaiyan/Moviz#4]
https://github.com/rezaiyan/Moviz/blob/a9cc67cdd5a91acccf09668664a2227cedb05532/data/src/main/java/ir/alirezaiyan/moviz/data/feature/search/SearchRepository.kt#L16

این کاری که کردی کلا اشتباه:
۱- ریپازیتوری باید تو لایه دومین ات باشه نه دیتا
۲- اون حالت نتورکی که تو ریپازیتوری پیاده کردی، درواقع datasource عه نه ریپازیتوری
یعنی باید به ایمپلیمنتیشن ریپازیتوری سرچ ات ورودی دیتا سورس های مختلف بدی.

**Comment by rezaiyan** [comment]
Was done in this commit https://github.com/rezaiyan/Moviz/commit/8849f3d902eda9237e0ff787bef91648534f0077
