### ISSUE TITLE
احتمال وقوع نال پوینتر

### ISSUE THREAD

**Issue by SaeedMasoumi** [rezaiyan/Moviz#5]
https://github.com/rezaiyan/Moviz/blob/a9cc67cdd5a91acccf09668664a2227cedb05532/app/src/main/java/ir/alirezaiyan/moviz/feature/search/SearchFragment.kt#L56

اینجا بهتره از let استفاده کنی

**Comment by rezaiyan** [comment]
Was fixed with this commit https://github.com/rezaiyan/Moviz/commit/a9574f8b313fa9bc6dc3b7229243b506155af2b7
